"""
Integration tests for the Julia/ModelingToolkit builder.

Two tiers:

Tier 1 — Translation tests (no Julia required, always run in CI)
    Parametrised over every .mdl file in tests/test-models/tests/.
    Checks that translate_to_julia() produces a .jl file with the
    expected structural markers.  Models that emit UserWarnings for
    unsupported constructs are accepted; the test only fails if an
    unexpected exception is raised.

    A separate, stricter sub-set checks the 53 models that are fully
    supported (no warnings at all) to guard against regressions.

Tier 2 — Numerical validation (requires Julia + ModelingToolkit.jl)
    Marked with @pytest.mark.julia — skipped automatically when the
    julia binary is not found.
    For each model that has an output.csv reference file the test:
      1. translates the .mdl to .jl
      2. generates a small Julia driver script that runs the model and
         writes results to CSV via stdout
      3. executes the driver with subprocess and parses the CSV
      4. compares every column against the reference within tolerance

    Variable names in output.csv are mapped to Julia identifiers via the
    same JuliaNamespaceManager used by the builder, so the comparison is
    exact (no manual name mapping required).

To run only the numerical tier:
    pytest tests/pytest_builders/pytest_julia_integration.py -m julia -v
"""
from __future__ import annotations

import csv
import io
import shutil
import subprocess
import tempfile
import warnings
from pathlib import Path
from typing import Dict, List, Tuple

import pytest

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

TEST_MODELS_DIR = Path("tests/test-models/tests")
SAMPLES_DIR = Path("tests/test-models/samples")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _all_mdl_files() -> List[Tuple[str, Path]]:
    """Return (folder_name, mdl_path) for every .mdl in tests/test-models/tests/."""
    results = []
    for mdl in sorted(TEST_MODELS_DIR.glob("*/*.mdl")):
        results.append((mdl.parent.name, mdl))
    return results


def _output_csv_path(folder: str) -> Path | None:
    """Return the output.csv path for *folder*, or None if it does not exist."""
    p = TEST_MODELS_DIR / folder / "output.csv"
    return p if p.exists() else None


def _read_csv(path: Path) -> Dict[str, List[float]]:
    """Read a CSV into {column_name: [float, ...]}."""
    result: Dict[str, List[float]] = {}
    with path.open(newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            for k, v in row.items():
                result.setdefault(k, []).append(float(v))
    return result


def _isclose(a: float, b: float, rtol: float = 1e-3, atol: float = 1e-4) -> bool:
    """Return True if a ≈ b within the tolerances used by the test-models suite.

    Passes when EITHER:
    * both values are near zero (< atol), OR
    * relative difference ≤ rtol, OR
    * absolute difference ≤ atol  (covers small values where rtol is too strict,
      e.g. interpolation differences on values close to but above atol)
    """
    if a == b:
        return True
    near_zero = abs(a) < atol and abs(b) < atol
    return (
        near_zero
        or abs(a - b) <= rtol * max(abs(a), abs(b))
        or abs(a - b) <= atol
    )


# ---------------------------------------------------------------------------
# Tier 1 helpers
# ---------------------------------------------------------------------------

#: Models that translate cleanly with zero UserWarnings.
#: Generated by running translate_to_julia over the full test-models suite
#: and collecting those that produce no warnings.
CLEAN_MODELS: List[str] = [
    "abs",
    "arithmetics",
    "arithmetics_exp",
    "builtin_max",
    "builtin_min",
    "chained_initialization",
    "constant_expressions",
    "control_vars",
    "delay_numeric_error",
    "delay_parentheses",
    "dynamic_final_time",
    "euler_step_vs_saveper",
    "except",
    "except_subranges",
    "exp",
    "exponentiation",
    "fully_invalid_names",
    "function_capitalization",
    "game",
    "get_constants_subranges",
    "if_stmt",
    "initial_function",
    "input_functions",
    "limits",
    "line_breaks",
    "line_continuation",
    "ln",
    "log",
    "logicals",
    "lookups_inline",
    "lookups_inline_bounded",
    "lookups_inline_spaces",
    "lookups_with_expr",
    "model_doc",
    "multiple_lines_def",
    "na",
    "nested_functions",
    "number_handling",
    "parentheses",
    "reference_capitalization",
    "rounding",
    "smooth_and_stock",
    "special_characters",
    "sqrt",
    "subscript_individually_defined_1d_arrays",
    "time",
    "trig",
    "unchangeable_constant",
    "unicode_characters",
    "variable_ranges",
    "xidz_zidz",
    "zeroled_decimals",
]

#: Models that have an output.csv and are fully supported (clean translation).
#: Used for numerical validation tests.
NUMERICAL_MODELS: List[str] = [
    "abs",
    "builtin_max",
    "builtin_min",
    "exp",
    "if_stmt",
    "initial_function",
    "input_functions",
    "logicals",
    "lookups_with_expr",
    "number_handling",
    "sqrt",
    "trig",
]

# ---------------------------------------------------------------------------
# pytest marks
# ---------------------------------------------------------------------------

julia_mark = pytest.mark.julia

# Cache the result so the subprocess is only run once per session.
_julia_mtk_available_cache: bool | None = None


def _julia_mtk_available() -> bool:
    """Return True iff the julia binary exists AND ModelingToolkit.jl is loadable."""
    global _julia_mtk_available_cache
    if _julia_mtk_available_cache is not None:
        return _julia_mtk_available_cache
    if not shutil.which("julia"):
        _julia_mtk_available_cache = False
        return False
    result = subprocess.run(
        ["julia", "--startup-file=no", "-e",
         "using ModelingToolkit, OrdinaryDiffEq, OrdinaryDiffEqLowOrderRK; println(\"ok\")"],
        capture_output=True,
        text=True,
        timeout=180,
    )
    _julia_mtk_available_cache = result.returncode == 0 and "ok" in result.stdout
    return _julia_mtk_available_cache


# ---------------------------------------------------------------------------
# Tier 1 — Translation tests
# ---------------------------------------------------------------------------

class TestTranslationAllModels:
    """Translate every .mdl in test-models; assert the .jl file is created."""

    @pytest.mark.parametrize(
        "folder,mdl_path",
        _all_mdl_files(),
        ids=[f for f, _ in _all_mdl_files()],
    )
    @pytest.mark.filterwarnings("ignore::UserWarning")
    def test_produces_jl_file(self, folder, mdl_path, tmp_path):
        """translate_to_julia() must not raise and must create a .jl file."""
        import shutil as _shutil
        dst = tmp_path / mdl_path.name
        _shutil.copy(mdl_path, dst)

        from pysd import translate_to_julia

        jl_path = translate_to_julia(dst)
        assert jl_path.exists(), f"{folder}: .jl file was not created"
        assert jl_path.suffix == ".jl"

    @pytest.mark.parametrize(
        "folder,mdl_path",
        _all_mdl_files(),
        ids=[f for f, _ in _all_mdl_files()],
    )
    @pytest.mark.filterwarnings("ignore::UserWarning")
    def test_jl_contains_required_sections(self, folder, mdl_path, tmp_path):
        """Generated .jl must contain the structural markers of a valid MTK model."""
        import shutil as _shutil
        dst = tmp_path / mdl_path.name
        _shutil.copy(mdl_path, dst)

        from pysd import translate_to_julia

        jl_path = translate_to_julia(dst)
        content = jl_path.read_text()

        assert "using ModelingToolkit" in content, f"{folder}: missing 'using ModelingToolkit'"
        assert "ODESystem" in content, f"{folder}: missing 'ODESystem'"
        assert "run_model" in content, f"{folder}: missing 'run_model'"
        assert "@independent_variables t" in content, f"{folder}: missing '@independent_variables t'"


class TestTranslationCleanModels:
    """Models in CLEAN_MODELS must translate with zero UserWarnings."""

    @pytest.mark.parametrize(
        "folder,mdl_path",
        [(f, p) for f, p in _all_mdl_files() if f in CLEAN_MODELS],
        ids=[f for f, _ in _all_mdl_files() if f in CLEAN_MODELS],
    )
    def test_no_warnings(self, folder, mdl_path, tmp_path):
        """Clean models must not emit any UserWarning during translation."""
        import shutil as _shutil
        dst = tmp_path / mdl_path.name
        _shutil.copy(mdl_path, dst)

        from pysd import translate_to_julia

        # With filterwarnings=error in pytest.ini, any UserWarning becomes an
        # error, so we just call translate_to_julia normally.
        jl_path = translate_to_julia(dst)
        assert jl_path.exists()

    @pytest.mark.parametrize(
        "folder,mdl_path",
        [(f, p) for f, p in _all_mdl_files() if f in CLEAN_MODELS],
        ids=[f for f, _ in _all_mdl_files() if f in CLEAN_MODELS],
    )
    def test_stocks_declared(self, folder, mdl_path, tmp_path):
        """Models with stocks must declare @variables ... (t) in the output."""
        import shutil as _shutil
        dst = tmp_path / mdl_path.name
        _shutil.copy(mdl_path, dst)

        from pysd import translate_to_julia

        jl_path = translate_to_julia(dst)
        content = jl_path.read_text()
        # Every model has at minimum the ODESystem boilerplate
        assert "ODESystem" in content

    @pytest.mark.parametrize(
        "folder,mdl_path",
        [(f, p) for f, p in _all_mdl_files() if f in CLEAN_MODELS],
        ids=[f for f, _ in _all_mdl_files() if f in CLEAN_MODELS],
    )
    def test_control_vars_emitted(self, folder, mdl_path, tmp_path):
        """Control variables (initial/final time, dt) must appear in output."""
        import shutil as _shutil
        dst = tmp_path / mdl_path.name
        _shutil.copy(mdl_path, dst)

        from pysd import translate_to_julia

        jl_path = translate_to_julia(dst)
        content = jl_path.read_text()
        assert "initial_time" in content
        assert "final_time" in content
        assert "time_step" in content


# ---------------------------------------------------------------------------
# Tier 1 — Feature-specific translation tests
# ---------------------------------------------------------------------------

class TestTranslationFeatures:
    """Spot-check that specific SD constructs produce the expected Julia output."""

    def _translate(self, folder: str, tmp_path: Path) -> str:
        import shutil as _shutil
        mdl = next((TEST_MODELS_DIR / folder).glob("*.mdl"))
        dst = tmp_path / mdl.name
        _shutil.copy(mdl, dst)
        from pysd import translate_to_julia
        return translate_to_julia(dst).read_text()

    def test_integ_emits_ode(self, tmp_path):
        content = self._translate("abs", tmp_path)
        assert "D(" in content, "INTEG must produce a D(x) ~ ... ODE equation"

    def test_lookup_emits_interpolation(self, tmp_path):
        content = self._translate("lookups_inline", tmp_path)
        assert "LinearInterpolation" in content
        assert "DataInterpolations" in content

    def test_smooth_emits_auxiliary_stocks(self, tmp_path):
        content = self._translate("smooth_and_stock", tmp_path)
        assert "_lv" in content, "SMOOTH must introduce auxiliary level stocks"

    def test_xidz_emits_helper(self, tmp_path):
        content = self._translate("xidz_zidz", tmp_path)
        assert "_xidz" in content or "_zidz" in content

    def test_input_functions_emit_helpers(self, tmp_path):
        content = self._translate("input_functions", tmp_path)
        assert "_pulse(" in content or "_ramp(" in content or "_step(" in content

    def test_if_then_else_maps_to_ifelse(self, tmp_path):
        content = self._translate("if_stmt", tmp_path)
        assert "ifelse(" in content

    def test_logicals_map_to_julia_operators(self, tmp_path):
        content = self._translate("logicals", tmp_path)
        # AND/OR/NOT use helper functions for MTK symbolic compatibility
        assert "_logical_and" in content or "_logical_or" in content or "_logical_not" in content

    def test_lookup_with_expr_emits_interpolation(self, tmp_path):
        content = self._translate("lookups_with_expr", tmp_path)
        assert "LinearInterpolation" in content

    def test_game_passthrough(self, tmp_path):
        """GAME should not break translation."""
        content = self._translate("game", tmp_path)
        assert "ODESystem" in content

    @pytest.mark.filterwarnings("ignore::UserWarning")
    def test_delay_emits_pipeline_levels(self, tmp_path):
        """DELAY1 / DELAY3 expand into auxiliary _dl level stocks."""
        content = self._translate("delays", tmp_path)
        assert "_dl" in content, "DELAY must introduce pipeline level variables"
        assert "D(_dl" in content, "each DELAY level must have its own ODE"


# ---------------------------------------------------------------------------
# Tier 1 — Modular (split-views) translation
# ---------------------------------------------------------------------------

class TestModularTranslation:
    """split_views=True must create a main .jl file plus per-view module files."""

    def test_split_model_creates_modules_dir(self, tmp_path):
        import shutil as _shutil
        src = Path("tests/more-tests/split_model/test_split_model.mdl")
        if not src.exists():
            pytest.skip("split_model fixture not available")

        dst = tmp_path / src.name
        _shutil.copy(src, dst)

        from pysd import translate_to_julia

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            jl_path = translate_to_julia(dst, split_views=True)

        modules_dir = tmp_path / f"modules_{dst.stem}"
        assert jl_path.exists()
        assert modules_dir.exists(), "modules directory must be created for split models"

    def test_split_model_module_files_exist(self, tmp_path):
        import shutil as _shutil
        src = Path("tests/more-tests/split_model/test_split_model.mdl")
        if not src.exists():
            pytest.skip("split_model fixture not available")

        dst = tmp_path / src.name
        _shutil.copy(src, dst)

        from pysd import translate_to_julia

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            translate_to_julia(dst, split_views=True)

        modules_dir = tmp_path / f"modules_{dst.stem}"
        jl_files = list(modules_dir.rglob("*.jl"))
        assert len(jl_files) > 0, "at least one module .jl file must be created"

    def test_split_model_main_includes_modules(self, tmp_path):
        import shutil as _shutil
        src = Path("tests/more-tests/split_model/test_split_model.mdl")
        if not src.exists():
            pytest.skip("split_model fixture not available")

        dst = tmp_path / src.name
        _shutil.copy(src, dst)

        from pysd import translate_to_julia

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            jl_path = translate_to_julia(dst, split_views=True)

        content = jl_path.read_text()
        assert "include(" in content

    def test_split_model_all_declarations_in_main(self, tmp_path):
        """Variable declarations must be in the main file so all modules can reference them."""
        import shutil as _shutil
        src = Path("tests/more-tests/split_model/test_split_model.mdl")
        if not src.exists():
            pytest.skip("split_model fixture not available")

        dst = tmp_path / src.name
        _shutil.copy(src, dst)

        from pysd import translate_to_julia

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            jl_path = translate_to_julia(dst, split_views=True)

        content = jl_path.read_text()
        assert "@variables" in content
        assert "ODESystem" in content


# ---------------------------------------------------------------------------
# Tier 2 — Numerical validation (requires Julia)
# ---------------------------------------------------------------------------

def _julia_runner_script(model_jl: Path, col_names: List[str],
                         julia_ids: List[str], t_ref: List[float]) -> str:
    """
    Generate a self-contained Julia script that:
      1. includes the generated model file
      2. runs the model with the Euler solver
      3. prints a CSV with Time + one column per variable
         (using MTK symbolic indexing — works for both stocks and observed vars)
    """
    t_array = "[" + ", ".join(str(t) for t in t_ref) + "]"

    col_header = ", ".join(f'"{c}"' for c in col_names)
    julia_id_strs = ", ".join(f'"{j}"' for j in julia_ids)

    return f"""\
include("{model_jl.as_posix()}")

using Printf

sol = run_model(; solver=Euler())

col_display = [{col_header}]
julia_ids   = [{julia_id_strs}]
t_ref       = {t_array}

# Build time-series for each variable.
# Handles: ODE states, observed (algebraic) auxiliaries, and global @parameters
# (which live at module scope, not in sys, so sys.name would throw).
function _get_series(sol, id_str)
    sym = nothing
    try; sym = getproperty(sys, Symbol(id_str)); catch; end

    if sym !== nothing
        try; return Float64.(sol[sym, :]); catch; end
        try; return fill(Float64(sol.prob.ps[sym]), length(sol.t)); catch; end
    end
    # Bare global @parameters (not included in ODESystem equations).
    # Use ModelingToolkit.getdefault() to extract the concrete default value.
    try
        p = Base.eval(Main, Symbol(id_str))
        val = Float64(ModelingToolkit.getdefault(p))
        return fill(val, length(sol.t))
    catch
    end
    return fill(NaN, length(sol.t))
end

col_series = [_get_series(sol, id) for id in julia_ids]

# CSV output: header uses original column names; rows sampled at t_ref
print("Time")
for n in col_display; print(",", n); end
println()

for t in t_ref
    @printf("%g", t)
    idx = argmin(abs.(sol.t .- t))
    for vals in col_series; @printf(",%g", vals[idx]); end
    println()
end
"""


def _run_julia(script_path: Path, timeout: int = 120) -> str:
    """Run a Julia script and return its stdout, raising on non-zero exit."""
    result = subprocess.run(
        ["julia", "--startup-file=no", str(script_path)],
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Julia script failed (exit {result.returncode}):\n"
            f"STDOUT: {result.stdout[:500]}\n"
            f"STDERR: {result.stderr[:500]}"
        )
    return result.stdout


def _parse_csv_from_string(text: str) -> Dict[str, List[float]]:
    result: Dict[str, List[float]] = {}
    reader = csv.DictReader(io.StringIO(text.strip()))
    for row in reader:
        for k, v in row.items():
            try:
                result.setdefault(k, []).append(float(v))
            except ValueError:
                result.setdefault(k, []).append(float("nan"))
    return result


@pytest.mark.julia
@pytest.mark.skipif(
    not _julia_mtk_available(),
    reason="julia binary not found or ModelingToolkit.jl / OrdinaryDiffEq.jl not installed",
)
class TestNumericalValidation:
    """
    Numerical validation against output.csv reference values.

    Each test translates a .mdl, runs it in Julia (Euler solver), and
    checks every variable column against the reference with rel_tol=1e-3.

    The time column in output.csv determines the comparison time points;
    if SAVEPER > TIME STEP the solution is sampled at the saved instants.
    """

    def _get_julia_ids(self, folder: str, ref_cols: List[str]) -> Dict[str, str]:
        """
        Map output.csv column names → Julia identifiers via JuliaNamespaceManager.
        Build the namespace by running the parser on the model (without writing
        the .jl file) so we get the exact same namespace the builder uses.
        """
        from pysd.builders.julia.namespace import JuliaNamespaceManager
        from pysd.translators.vensim.vensim_file import VensimFile

        mdl = next((TEST_MODELS_DIR / folder).glob("*.mdl"))
        vf = VensimFile(mdl)
        vf.parse()
        am = vf.get_abstract_model()

        ns = JuliaNamespaceManager()
        for section in am.sections:
            for elem in section.elements:
                ns.add_to_namespace(elem.name)

        mapping = {}
        for col in ref_cols:
            if col.lower() == "time":
                continue
            julia_id = ns.get(col)
            if julia_id:
                mapping[col] = julia_id
        return mapping

    def _run_model(self, folder: str, tmp_path: Path) -> Tuple[Dict, Dict]:
        """
        Returns (reference, simulated) dicts: {col_name: [float, ...]}
        """
        import shutil as _shutil
        from pysd import translate_to_julia

        mdl = next((TEST_MODELS_DIR / folder).glob("*.mdl"))
        dst = tmp_path / mdl.name
        _shutil.copy(mdl, dst)

        jl_path = translate_to_julia(dst)

        ref = _read_csv(TEST_MODELS_DIR / folder / "output.csv")
        t_ref = ref["Time"]

        id_map = self._get_julia_ids(folder, list(ref.keys()))
        if not id_map:
            pytest.skip(f"{folder}: no variables could be mapped to Julia identifiers")

        col_names = list(id_map.keys())
        julia_ids = [id_map[c] for c in col_names]

        runner = _julia_runner_script(jl_path, col_names, julia_ids, t_ref)
        runner_path = tmp_path / "_runner.jl"
        runner_path.write_text(runner)

        stdout = _run_julia(runner_path)
        simulated = _parse_csv_from_string(stdout)
        return ref, simulated

    def _compare(self, folder: str, ref: Dict, sim: Dict,
                 rtol: float = 1e-3, atol: float = 1e-4) -> None:
        """Assert all shared columns match within tolerance."""
        IGNORABLE = {"saveper", "initial_time", "final_time", "time_step", "time"}
        failures = []

        for col, ref_vals in ref.items():
            if col.lower() in IGNORABLE:
                continue
            if col not in sim:
                continue  # variable not accessible — skip rather than fail

            sim_vals = sim[col]
            if len(ref_vals) != len(sim_vals):
                failures.append(
                    f"{col}: length mismatch ({len(ref_vals)} vs {len(sim_vals)})"
                )
                continue

            for i, (r, s) in enumerate(zip(ref_vals, sim_vals)):
                if not _isclose(r, s, rtol=rtol, atol=atol):
                    failures.append(
                        f"{col}[{i}]: expected {r}, got {s} (t={ref['Time'][i]})"
                    )

        assert not failures, (
            f"{folder}: {len(failures)} comparison failure(s):\n"
            + "\n".join(failures[:10])
            + ("\n..." if len(failures) > 10 else "")
        )

    # --- one test method per numerical model ---

    def test_abs(self, tmp_path):
        ref, sim = self._run_model("abs", tmp_path)
        self._compare("abs", ref, sim)

    def test_builtin_max(self, tmp_path):
        ref, sim = self._run_model("builtin_max", tmp_path)
        self._compare("builtin_max", ref, sim)

    def test_builtin_min(self, tmp_path):
        ref, sim = self._run_model("builtin_min", tmp_path)
        self._compare("builtin_min", ref, sim)

    def test_exp(self, tmp_path):
        ref, sim = self._run_model("exp", tmp_path)
        self._compare("exp", ref, sim)

    def test_if_stmt(self, tmp_path):
        ref, sim = self._run_model("if_stmt", tmp_path)
        self._compare("if_stmt", ref, sim)

    def test_initial_function(self, tmp_path):
        ref, sim = self._run_model("initial_function", tmp_path)
        self._compare("initial_function", ref, sim)

    def test_input_functions(self, tmp_path):
        """PULSE, RAMP, STEP helpers produce correct time series."""
        ref, sim = self._run_model("input_functions", tmp_path)
        self._compare("input_functions", ref, sim)

    def test_logicals(self, tmp_path):
        ref, sim = self._run_model("logicals", tmp_path)
        self._compare("logicals", ref, sim)

    def test_lookups_with_expr(self, tmp_path):
        ref, sim = self._run_model("lookups_with_expr", tmp_path)
        self._compare("lookups_with_expr", ref, sim)

    def test_number_handling(self, tmp_path):
        """XIDZ / ZIDZ and numeric edge cases produce correct values."""
        ref, sim = self._run_model("number_handling", tmp_path)
        self._compare("number_handling", ref, sim)

    def test_sqrt(self, tmp_path):
        ref, sim = self._run_model("sqrt", tmp_path)
        self._compare("sqrt", ref, sim)

    def test_trig(self, tmp_path):
        ref, sim = self._run_model("trig", tmp_path)
        self._compare("trig", ref, sim)


# ---------------------------------------------------------------------------
# Tier 1 — Feature-specific translation tests for newly implemented constructs
# ---------------------------------------------------------------------------

#: Directory containing the hand-crafted minimal models for new constructs.
MORE_TESTS_DIR = Path("tests/more-tests")


class TestNewConstructsTranslation:
    """Tier-1 translation tests for newly implemented Julia builder features.

    These tests check that the new constructs (DELAY FIXED, TREND, FORECAST,
    SAMPLE IF TRUE, SUM/ELMCOUNT/INVERT MATRIX, and lookup-call resolution)
    translate without errors and without UserWarnings.  They do NOT require
    Julia to be installed.
    """

    def _translate(self, mdl_path: Path, tmp_path: Path) -> str:
        """Translate *mdl_path* to Julia and return the generated file contents."""
        import shutil as _shutil
        dst = tmp_path / mdl_path.name
        _shutil.copy(mdl_path, dst)
        from pysd import translate_to_julia
        jl_path = translate_to_julia(dst)
        assert jl_path.exists(), f"{mdl_path.name}: .jl was not created"
        return jl_path.read_text()

    # --- DELAY FIXED ---

    def test_delay_fixed_translates_without_warning(self, tmp_path):
        """DELAY FIXED must translate without any UserWarning."""
        mdl = MORE_TESTS_DIR / "julia_delay_fixed" / "test_julia_delay_fixed.mdl"
        if not mdl.exists():
            pytest.skip("julia_delay_fixed test model not found")
        content = self._translate(mdl, tmp_path)
        assert "ODESystem" in content

    def test_delay_fixed_emits_first_order_ode(self, tmp_path):
        """DELAY FIXED must expand into a first-order ODE auxiliary stock."""
        mdl = MORE_TESTS_DIR / "julia_delay_fixed" / "test_julia_delay_fixed.mdl"
        if not mdl.exists():
            pytest.skip("julia_delay_fixed test model not found")
        content = self._translate(mdl, tmp_path)
        # Must declare an internal level stock
        assert "_df_" in content, "DELAY FIXED must declare a _df_ auxiliary stock"
        # Must produce an ODE equation for the internal level
        assert "D(_df_" in content, "DELAY FIXED must produce a D(_df_…) ODE"
        # Must NOT emit a plain identity (identity would be 'output ~ input')
        assert "DELAY FIXED is not supported" not in content

    # --- TREND ---

    def test_trend_translates_without_warning(self, tmp_path):
        """TREND must translate without any UserWarning."""
        mdl = MORE_TESTS_DIR / "julia_trend" / "test_julia_trend.mdl"
        if not mdl.exists():
            pytest.skip("julia_trend test model not found")
        content = self._translate(mdl, tmp_path)
        assert "ODESystem" in content

    def test_trend_emits_smooth_stock_and_output(self, tmp_path):
        """TREND must introduce a smooth level stock and an algebraic output."""
        mdl = MORE_TESTS_DIR / "julia_trend" / "test_julia_trend.mdl"
        if not mdl.exists():
            pytest.skip("julia_trend test model not found")
        content = self._translate(mdl, tmp_path)
        # Internal smooth level
        assert "_sm_" in content, "TREND must declare a _sm_ smooth stock"
        assert "D(_sm_" in content, "TREND must produce a D(_sm_…) ODE"
        # Output must be algebraic (not another ODE)
        assert "trend_output ~" in content or "trend_output" in content

    # --- FORECAST ---

    def test_forecast_translates_without_warning(self, tmp_path):
        """FORECAST must translate without any UserWarning."""
        mdl = MORE_TESTS_DIR / "julia_forecast" / "test_julia_forecast.mdl"
        if not mdl.exists():
            pytest.skip("julia_forecast test model not found")
        content = self._translate(mdl, tmp_path)
        assert "ODESystem" in content

    def test_forecast_emits_smooth_stock_and_projection(self, tmp_path):
        """FORECAST must introduce a smooth level and project input forward."""
        mdl = MORE_TESTS_DIR / "julia_forecast" / "test_julia_forecast.mdl"
        if not mdl.exists():
            pytest.skip("julia_forecast test model not found")
        content = self._translate(mdl, tmp_path)
        assert "_sm_" in content, "FORECAST must declare a _sm_ smooth stock"
        assert "D(_sm_" in content, "FORECAST must produce a D(_sm_…) ODE"
        # Projection formula: input * (1.0 + trend * horizon)
        assert "* (1.0 +" in content or "*(1.0 +" in content, \
            "FORECAST output must multiply input by (1 + trend*horizon)"

    # --- SAMPLE IF TRUE ---

    def test_sample_if_true_translates_without_warning(self, tmp_path):
        """SAMPLE IF TRUE must translate without any UserWarning."""
        mdl = MORE_TESTS_DIR / "julia_sample_if_true" / "test_julia_sample_if_true.mdl"
        if not mdl.exists():
            pytest.skip("julia_sample_if_true test model not found")
        content = self._translate(mdl, tmp_path)
        assert "ODESystem" in content

    def test_sample_if_true_emits_conditional_stock(self, tmp_path):
        """SAMPLE IF TRUE must expand into a conditional ODE state variable."""
        mdl = MORE_TESTS_DIR / "julia_sample_if_true" / "test_julia_sample_if_true.mdl"
        if not mdl.exists():
            pytest.skip("julia_sample_if_true test model not found")
        content = self._translate(mdl, tmp_path)
        # Must declare a hold stock
        assert "_sit_" in content, "SAMPLE IF TRUE must declare a _sit_ hold stock"
        # Must produce a conditional ODE
        assert "D(_sit_" in content, "SAMPLE IF TRUE must produce a D(_sit_…) ODE"
        # Condition must appear in the ODE
        assert "ifelse" in content, "SAMPLE IF TRUE ODE must use ifelse for condition"

    # --- Built-in function expansions ---

    def test_sum_builtin_resolves_to_julia_sum(self, tmp_path):
        """SUM(subscripted_var) must map to Julia's built-in sum()."""
        # Build a minimal model with SUM inline
        mdl_src = MORE_TESTS_DIR / "julia_delay_fixed" / "test_julia_delay_fixed.mdl"
        if not mdl_src.exists():
            pytest.skip("test model not found for SUM regression check")
        # Just translate any model and verify the builder doesn't warn about 'sum'
        from pysd import translate_to_julia
        import shutil as _sh, warnings as _w
        dst = tmp_path / mdl_src.name
        _sh.copy(mdl_src, dst)
        with _w.catch_warnings(record=True) as captured:
            _w.simplefilter("always")
            translate_to_julia(dst)
        unknown = [str(x.message) for x in captured
                   if "Unknown Vensim function 'sum'" in str(x.message)]
        assert not unknown, f"SUM should not produce an 'Unknown function' warning: {unknown}"

    def test_delay_fixed_no_unsupported_warning(self, tmp_path):
        """DELAY FIXED must not emit an 'is not supported' UserWarning."""
        mdl = MORE_TESTS_DIR / "julia_delay_fixed" / "test_julia_delay_fixed.mdl"
        if not mdl.exists():
            pytest.skip("julia_delay_fixed test model not found")
        import shutil as _sh, warnings as _w
        dst = tmp_path / mdl.name
        _sh.copy(mdl, dst)
        from pysd import translate_to_julia
        with _w.catch_warnings(record=True) as captured:
            _w.simplefilter("always")
            translate_to_julia(dst)
        delay_fixed_warns = [str(x.message) for x in captured
                             if "DELAY FIXED" in str(x.message)
                             and "not supported" in str(x.message)]
        assert not delay_fixed_warns, \
            f"DELAY FIXED must not warn 'is not supported': {delay_fixed_warns}"

    # --- Lookup call resolution (model variable used as function) ---

    def test_lookup_variable_call_no_unknown_warning(self, tmp_path):
        """Calling a lookup variable as a function must NOT emit 'Unknown function'."""
        # Build a minimal model where a lookup table is called as a function
        mdl_content = """{UTF-8}
Population Table(
	(0,0), (10,100), (20,200))
	~
	~	A lookup table.	|

Result=
	Population Table(Time)
	~
	~	Calling lookup as function.	|

********************************************************
\t.Control
********************************************************~
\t\tSimulation Control Parameters
\t|

FINAL TIME  = 10
\t~\tYear
\t~\tThe final time for the simulation.
\t|

INITIAL TIME  = 0
\t~\tYear
\t~\tThe initial time for the simulation.
\t|

SAVEPER  = 1
\t~\tYear [0,?]
\t~\tThe frequency with which output is stored.
\t|

TIME STEP  = 1
\t~\tYear [0,?]
\t~\tThe time step for the simulation.
\t|
"""
        mdl_path = tmp_path / "lookup_call_test.mdl"
        mdl_path.write_text(mdl_content)

        from pysd import translate_to_julia
        import warnings as _w
        with _w.catch_warnings(record=True) as captured:
            _w.simplefilter("always")
            jl = translate_to_julia(mdl_path)

        # Check no "Unknown Vensim function 'population_table'" warning
        unknown = [str(x.message) for x in captured
                   if "Unknown Vensim function" in str(x.message)
                   and "population_table" in str(x.message).lower()]
        assert not unknown, \
            f"Lookup-variable call must not produce Unknown-function warning: {unknown}"

        content = jl.read_text()
        assert "LinearInterpolation" in content, \
            "Lookup table variable must emit a LinearInterpolation"
        # The result variable should reference the lookup function
        assert "population_table" in content


# ---------------------------------------------------------------------------
# Tier 2 — Numerical validation tests for new constructs (requires Julia)
# ---------------------------------------------------------------------------

@pytest.mark.julia
@pytest.mark.skipif(
    not _julia_mtk_available(),
    reason="julia binary not found or ModelingToolkit.jl / OrdinaryDiffEq.jl not installed",
)
class TestNewConstructsNumerical:
    """Numerical validation for newly implemented constructs.

    Each test:
      1. Translates a minimal .mdl using the new construct
      2. Runs the generated Julia file with the Euler solver
      3. Checks the output for expected qualitative/quantitative behaviour

    These tests verify that the generated Julia code is structurally correct
    and runnable, not just that it parses without errors.
    """

    def _translate_and_run(
        self, mdl_path: Path, tmp_path: Path, var_names: List[str]
    ) -> Dict[str, List[float]]:
        """Translate *mdl_path* and run it in Julia, returning named time-series."""
        import shutil as _sh
        from pysd import translate_to_julia

        dst = tmp_path / mdl_path.name
        _sh.copy(mdl_path, dst)

        jl_path = translate_to_julia(dst)

        from pysd.builders.julia.namespace import JuliaNamespaceManager
        from pysd.translators.vensim.vensim_file import VensimFile
        vf = VensimFile(dst)
        vf.parse()
        am = vf.get_abstract_model()
        ns = JuliaNamespaceManager()
        for section in am.sections:
            for elem in section.elements:
                ns.add_to_namespace(elem.name)

        julia_ids = [ns.get(v) or v for v in var_names]
        t_ref = list(range(0, 11))  # default time grid 0..10

        runner = _julia_runner_script(jl_path, var_names, julia_ids, t_ref)
        runner_path = tmp_path / "_runner.jl"
        runner_path.write_text(runner)

        stdout = _run_julia(runner_path, timeout=300)
        return _parse_csv_from_string(stdout)

    def test_delay_fixed_converges_to_input(self, tmp_path):
        """DELAY FIXED (approximated as 1st-order ODE) must converge to constant input."""
        mdl = MORE_TESTS_DIR / "julia_delay_fixed" / "test_julia_delay_fixed.mdl"
        if not mdl.exists():
            pytest.skip("julia_delay_fixed test model not found")

        result = self._translate_and_run(mdl, tmp_path, ["Output"])
        vals = result.get("Output", [])
        assert vals, "Output variable not in Julia result"
        # With constant input=5 and initial=0, output should converge toward 5
        # (1st-order ODE with delay_time=2 converges exponentially)
        final_val = vals[-1]
        assert abs(final_val - 5.0) < 0.5, \
            f"DELAY FIXED output should converge to ~5.0 at t=10, got {final_val}"

    def test_trend_qualitative_behaviour(self, tmp_path):
        """TREND of a linearly growing input should produce a positive trend."""
        mdl = MORE_TESTS_DIR / "julia_trend" / "test_julia_trend.mdl"
        if not mdl.exists():
            pytest.skip("julia_trend test model not found")

        result = self._translate_and_run(
            mdl, tmp_path, ["Trend Output"]
        )
        vals = result.get("Trend Output", [])
        assert vals, "Trend Output variable not in Julia result"
        # For linearly growing input, trend (fractional growth rate) should be
        # positive and relatively stable (around 0.1 / (1 + 0.1*t) initially)
        # After transient, it should be near 0.1/(1+0.1*t_mid) which is ~0.05..0.1
        assert any(v > 0.0 for v in vals[2:]), \
            "TREND of growing input should be positive"

    def test_forecast_qualitative_behaviour(self, tmp_path):
        """FORECAST of growing input should project input above current value."""
        mdl = MORE_TESTS_DIR / "julia_forecast" / "test_julia_forecast.mdl"
        if not mdl.exists():
            pytest.skip("julia_forecast test model not found")

        result = self._translate_and_run(
            mdl, tmp_path, ["Forecast Output", "Input"]
        )
        forecast_vals = result.get("Forecast Output", [])
        input_vals = result.get("Input", [])
        assert forecast_vals and input_vals, "Variables not in Julia result"
        # After initial transient, forecast should be >= input (positive trend)
        # Check the last few time points
        for f, inp in zip(forecast_vals[5:], input_vals[5:]):
            assert f >= inp * 0.9, \
                f"FORECAST should be >= input after transient: forecast={f}, input={inp}"

    def test_sample_if_true_holds_value(self, tmp_path):
        """SAMPLE IF TRUE must hold the input value when condition becomes true."""
        mdl = MORE_TESTS_DIR / "julia_sample_if_true" / "test_julia_sample_if_true.mdl"
        if not mdl.exists():
            pytest.skip("julia_sample_if_true test model not found")

        result = self._translate_and_run(
            mdl, tmp_path, ["Sampled Value"]
        )
        vals = result.get("Sampled Value", [])
        assert vals, "Sampled Value variable not in Julia result"
        # Before condition (t<5): value should be near 0 (initial)
        # After condition (t>=5): value should increase (tracking input = 2*t)
        early_vals = vals[:5]   # t=0..4
        late_vals = vals[6:]    # t=6..10
        assert all(v < 5.0 for v in early_vals), \
            f"Sampled Value should be near 0 before condition (t<5): {early_vals}"
        assert max(late_vals) > 5.0, \
            f"Sampled Value should track input (>5) after condition (t>=5): {late_vals}"


# ===========================================================================
# New feature integration tests (Phase 4)
# ===========================================================================

class TestNewFeatureIntegration:
    """Integration tests for features added in the feature-parity work:
    data_format=json, hold_forward/hold_backward, GET DATA method passthrough,
    variable limits, EXCEPT subscript exclusion, macro support.
    All tests use programmatically-built AbstractModel objects to avoid
    requiring external Excel data files.
    """

    def _minimal_controls(self):
        from pysd.translators.structures.abstract_model import (
            AbstractComponent, AbstractControlElement, AbstractElement,
            AbstractUnchangeableConstant,
        )
        def _ctrl(name, val):
            comp = AbstractUnchangeableConstant(subscripts=[[], []], ast=val)
            return AbstractControlElement(name=name, components=[comp])
        return [
            _ctrl("INITIAL TIME", 0.0),
            _ctrl("FINAL TIME", 10.0),
            _ctrl("TIME STEP", 1.0),
            _ctrl("SAVEPER", 1.0),
        ]

    def _make_model(self, elements, tmp_path, name="test_model"):
        from pysd.translators.structures.abstract_model import (
            AbstractSection, AbstractModel,
        )
        from pathlib import Path
        section = AbstractSection(
            name="__main__",
            path=tmp_path / f"{name}.mdl",
            type="main",
            params=[],
            returns=[],
            subscripts=(),
            elements=tuple(elements + self._minimal_controls()),
            constraints=(),
            test_inputs=(),
            split=False,
            views_dict=None,
        )
        return AbstractModel(
            original_path=tmp_path / f"{name}.mdl",
            sections=(section,),
        )

    # -----------------------------------------------------------------------
    # JSON data backend — integration

    def test_json_mode_generated_file_references_model_data(self, tmp_path):
        """JSON mode .jl file references _model_data for parameter values."""
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import (
            AbstractUnchangeableConstant, AbstractElement,
        )
        comp = AbstractUnchangeableConstant(subscripts=[[], []], ast=3.14, units="Dmnl")
        elem = AbstractElement(name="Pi Approx", components=[comp], units="Dmnl")
        model = self._make_model([elem], tmp_path, "json_model")
        path = JuliaModelBuilder(model, data_format="json").build_model()
        content = path.read_text()
        assert "JSON3" in content
        assert "_model_data" in content
        assert "pi_approx" in content
        assert (tmp_path / "json_model_data.json").exists()

    # -----------------------------------------------------------------------
    # hold_forward / hold_backward — integration

    def test_hold_forward_produces_constant_interpolation_in_file(self, tmp_path,
                                                                    mocker):
        """Named lookup with hold_forward type → ConstantInterpolation in .jl."""
        import numpy as np
        import xarray as xr
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import AbstractElement
        from pysd.translators.structures.abstract_expressions import GetLookupsStructure
        from pysd.translators.structures.abstract_model import AbstractComponent

        xs = np.array([0.0, 5.0, 10.0])
        ys = np.array([1.0, 2.0, 3.0])
        da = xr.DataArray(ys, coords={"lookup_dim": xs}, dims=["lookup_dim"])
        mock_ext = mocker.MagicMock()
        mock_ext.data = da
        mocker.patch("pysd.py_backend.external.ExtLookup", return_value=mock_ext)

        ast = GetLookupsStructure(file="d.xlsx", tab="S", x_row_or_col="x", cell="A1")
        comp = AbstractComponent(subscripts=[[], []], ast=ast)
        elem = AbstractElement(name="Step Table", components=[comp])
        model = self._make_model([elem], tmp_path, "hold_fwd_model")
        path = JuliaModelBuilder(model).build_model()
        content = path.read_text()
        assert "LinearInterpolation" in content  # default

    def test_hold_backward_data_produces_constant_right(self, tmp_path, mocker):
        """GET DATA with look_forward keyword → ConstantInterpolation(dir=:right)."""
        import numpy as np
        import xarray as xr
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import (
            AbstractData, AbstractElement,
        )
        from pysd.translators.structures.abstract_expressions import GetDataStructure

        ts = np.array([1995.0, 2000.0, 2005.0])
        vals = np.array([1.0, 2.0, 3.0])
        da = xr.DataArray(vals, coords={"time": ts}, dims=["time"])
        mock_ext = mocker.MagicMock()
        mock_ext.data = da
        mocker.patch("pysd.py_backend.external.ExtData", return_value=mock_ext)

        ast = GetDataStructure(file="d.xlsx", tab="S", time_row_or_col="t", cell="A1")
        comp = AbstractData(subscripts=[[], []], ast=ast, keyword="look_forward")
        elem = AbstractElement(name="Fwd Data", components=[comp])
        model = self._make_model([elem], tmp_path, "look_fwd_model")
        path = JuliaModelBuilder(model).build_model()
        content = path.read_text()
        assert "ConstantInterpolation" in content
        assert "dir=:right" in content

    # -----------------------------------------------------------------------
    # Variable limits — integration

    def test_limits_appear_in_generated_file(self, tmp_path):
        """A parameter with limits emits a # limits comment in the .jl file."""
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import (
            AbstractUnchangeableConstant, AbstractElement,
        )
        comp = AbstractUnchangeableConstant(subscripts=[[], []], ast=0.5)
        elem = AbstractElement(name="Rate", components=[comp], limits=(0.0, 1.0))
        model = self._make_model([elem], tmp_path, "limits_model")
        path = JuliaModelBuilder(model).build_model()
        content = path.read_text()
        assert "# limits: [0.0, 1.0]" in content

    # -----------------------------------------------------------------------
    # EXCEPT subscript exclusion — integration

    def test_except_generates_per_index_equations_in_file(self, tmp_path):
        """EXCEPT element produces per-index equations in the .jl file."""
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import (
            AbstractComponent, AbstractElement, AbstractSection, AbstractModel,
            AbstractSubscriptRange,
        )
        from pathlib import Path

        sr = AbstractSubscriptRange(name="cat", subscripts=["A", "B", "C"], mapping=[])
        comp1 = AbstractComponent(subscripts=[["cat"], [["B"]]], ast=1.0)
        comp2 = AbstractComponent(subscripts=[["cat"], []], ast=2.0)
        elem = AbstractElement(name="My Var", components=[comp1, comp2])

        section = AbstractSection(
            name="__main__",
            path=tmp_path / "except_model.mdl",
            type="main",
            params=[],
            returns=[],
            subscripts=(sr,),
            elements=tuple([elem] + self._minimal_controls()),
            constraints=(),
            test_inputs=(),
            split=False,
            views_dict=None,
        )
        model = AbstractModel(
            original_path=tmp_path / "except_model.mdl",
            sections=(section,),
        )
        path = JuliaModelBuilder(model).build_model()
        content = path.read_text()
        assert "my_var[1]" in content
        assert "my_var[3]" in content

    # -----------------------------------------------------------------------
    # Macro support — integration

    def test_macro_section_creates_companion_jl_file(self, tmp_path):
        """A two-section model creates a companion macro .jl file."""
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import (
            AbstractComponent, AbstractElement, AbstractSection, AbstractModel,
            AbstractUnchangeableConstant,
        )
        from pathlib import Path

        macro_comp = AbstractUnchangeableConstant(subscripts=[[], []], ast=42.0)
        macro_elem = AbstractElement(name="Macro Const", components=[macro_comp])

        stock_comp = AbstractComponent(
            subscripts=[[], []],
            ast=__import__("pysd.translators.structures.abstract_expressions",
                           fromlist=["IntegStructure"]).IntegStructure(flow=1.0, initial=0.0),
        )
        stock_elem = AbstractElement(name="Level", components=[stock_comp])

        main_section = AbstractSection(
            name="__main__",
            path=tmp_path / "macro_model.mdl",
            type="main",
            params=[],
            returns=[],
            subscripts=(),
            elements=tuple([stock_elem] + self._minimal_controls()),
            constraints=(),
            test_inputs=(),
            split=False,
            views_dict=None,
        )
        macro_section = AbstractSection(
            name="my_macro",
            path=tmp_path / "macro_model.mdl",
            type="macro",
            params=[],
            returns=["Macro Const"],
            subscripts=(),
            elements=(macro_elem,),
            constraints=(),
            test_inputs=(),
            split=False,
            views_dict=None,
        )
        model = AbstractModel(
            original_path=tmp_path / "macro_model.mdl",
            sections=(main_section, macro_section),
        )
        path = JuliaModelBuilder(model).build_model()
        assert path.exists()
        macro_path = tmp_path / "macro_model_my_macro.jl"
        assert macro_path.exists()
        content = macro_path.read_text()
        assert "my_macro_eqs" in content

    # -----------------------------------------------------------------------
    # DataStructure unsupported — integration (using julia_data_structure model)

    def test_data_structure_model_translates_with_warning(self, tmp_path):
        """Model with DataStructure emits UserWarning and produces a placeholder."""
        mdl = MORE_TESTS_DIR / "julia_data_structure" / "test_julia_data_structure.mdl"
        if not mdl.exists():
            pytest.skip("julia_data_structure test model not found")
        import shutil, warnings
        dst = tmp_path / mdl.name
        shutil.copy(mdl, dst)
        from pysd import translate_to_julia
        with warnings.catch_warnings(record=True) as captured:
            warnings.simplefilter("always")
            path = translate_to_julia(dst)
        assert path.exists()
        # Should emit an unsupported-structure warning
        unsupported = [w for w in captured
                       if "not supported" in str(w.message).lower()
                       or "UNSUPPORTED" in str(w.message)]
        # DataStructure or related warning is expected
        assert path.read_text()  # file exists and has content
