"""
Integration tests for the Julia/ModelingToolkit builder.

Two tiers:

Tier 1 — Translation tests (no Julia required, always run in CI)
    Parametrised over every .mdl file in tests/test-models/tests/.
    Checks that translate_to_julia() produces a .jl file with the
    expected structural markers.  Models that emit UserWarnings for
    unsupported constructs are accepted; the test only fails if an
    unexpected exception is raised.

    A separate, stricter sub-set checks the 53 models that are fully
    supported (no warnings at all) to guard against regressions.

Tier 2 — Numerical validation (requires Julia + ModelingToolkit.jl)
    Marked with @pytest.mark.julia — skipped automatically when the
    julia binary is not found.
    For each model that has an output.csv reference file the test:
      1. translates the .mdl to .jl
      2. generates a small Julia driver script that runs the model and
         writes results to CSV via stdout
      3. executes the driver with subprocess and parses the CSV
      4. compares every column against the reference within tolerance

    Variable names in output.csv are mapped to Julia identifiers via the
    same JuliaNamespaceManager used by the builder, so the comparison is
    exact (no manual name mapping required).

To run only the numerical tier:
    pytest tests/pytest_builders/pytest_julia_integration.py -m julia -v
"""
from __future__ import annotations

import csv
import io
import shutil
import subprocess
import tempfile
import warnings
from pathlib import Path
from typing import Dict, List, Tuple

import pytest

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

TEST_MODELS_DIR = Path("tests/test-models/tests")
SAMPLES_DIR = Path("tests/test-models/samples")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _all_mdl_files() -> List[Tuple[str, Path]]:
    """Return (folder_name, mdl_path) for every .mdl in tests/test-models/tests/."""
    results = []
    for mdl in sorted(TEST_MODELS_DIR.glob("*/*.mdl")):
        results.append((mdl.parent.name, mdl))
    return results


def _output_csv_path(folder: str) -> Path | None:
    """Return the output.csv path for *folder*, or None if it does not exist."""
    p = TEST_MODELS_DIR / folder / "output.csv"
    return p if p.exists() else None


def _read_csv(path: Path) -> Dict[str, List[float]]:
    """Read a CSV into {column_name: [float, ...]}."""
    result: Dict[str, List[float]] = {}
    with path.open(newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            for k, v in row.items():
                result.setdefault(k, []).append(float(v))
    return result


def _isclose(a: float, b: float, rtol: float = 1e-3, atol: float = 1e-4) -> bool:
    """Return True if a ≈ b within the tolerances used by the test-models suite."""
    if a == b:
        return True
    near_zero = abs(a) < atol and abs(b) < atol
    return near_zero or abs(a - b) <= rtol * max(abs(a), abs(b))


# ---------------------------------------------------------------------------
# Tier 1 helpers
# ---------------------------------------------------------------------------

#: Models that translate cleanly with zero UserWarnings.
#: Generated by running translate_to_julia over the full test-models suite
#: and collecting those that produce no warnings.
CLEAN_MODELS: List[str] = [
    "abs",
    "arithmetics",
    "arithmetics_exp",
    "builtin_max",
    "builtin_min",
    "chained_initialization",
    "constant_expressions",
    "control_vars",
    "delay_numeric_error",
    "delay_parentheses",
    "dynamic_final_time",
    "euler_step_vs_saveper",
    "except",
    "except_subranges",
    "exp",
    "exponentiation",
    "fully_invalid_names",
    "function_capitalization",
    "game",
    "get_constants_subranges",
    "if_stmt",
    "initial_function",
    "input_functions",
    "limits",
    "line_breaks",
    "line_continuation",
    "ln",
    "log",
    "logicals",
    "lookups_inline",
    "lookups_inline_bounded",
    "lookups_inline_spaces",
    "lookups_with_expr",
    "model_doc",
    "multiple_lines_def",
    "na",
    "nested_functions",
    "number_handling",
    "parentheses",
    "reference_capitalization",
    "rounding",
    "smooth_and_stock",
    "special_characters",
    "sqrt",
    "subscript_individually_defined_1d_arrays",
    "time",
    "trig",
    "unchangeable_constant",
    "unicode_characters",
    "variable_ranges",
    "xidz_zidz",
    "zeroled_decimals",
]

#: Models that have an output.csv and are fully supported (clean translation).
#: Used for numerical validation tests.
NUMERICAL_MODELS: List[str] = [
    "abs",
    "builtin_max",
    "builtin_min",
    "exp",
    "if_stmt",
    "initial_function",
    "input_functions",
    "logicals",
    "lookups_with_expr",
    "number_handling",
    "sqrt",
    "trig",
]

# ---------------------------------------------------------------------------
# pytest marks
# ---------------------------------------------------------------------------

julia_mark = pytest.mark.julia

# Cache the result so the subprocess is only run once per session.
_julia_mtk_available_cache: bool | None = None


def _julia_mtk_available() -> bool:
    """Return True iff the julia binary exists AND ModelingToolkit.jl is loadable."""
    global _julia_mtk_available_cache
    if _julia_mtk_available_cache is not None:
        return _julia_mtk_available_cache
    if not shutil.which("julia"):
        _julia_mtk_available_cache = False
        return False
    result = subprocess.run(
        ["julia", "--startup-file=no", "-e",
         "using ModelingToolkit, OrdinaryDiffEq; println(\"ok\")"],
        capture_output=True,
        text=True,
        timeout=180,
    )
    _julia_mtk_available_cache = result.returncode == 0 and "ok" in result.stdout
    return _julia_mtk_available_cache


# ---------------------------------------------------------------------------
# Tier 1 — Translation tests
# ---------------------------------------------------------------------------

class TestTranslationAllModels:
    """Translate every .mdl in test-models; assert the .jl file is created."""

    @pytest.mark.parametrize(
        "folder,mdl_path",
        _all_mdl_files(),
        ids=[f for f, _ in _all_mdl_files()],
    )
    @pytest.mark.filterwarnings("ignore::UserWarning")
    def test_produces_jl_file(self, folder, mdl_path, tmp_path):
        """translate_to_julia() must not raise and must create a .jl file."""
        import shutil as _shutil
        dst = tmp_path / mdl_path.name
        _shutil.copy(mdl_path, dst)

        from pysd import translate_to_julia

        jl_path = translate_to_julia(dst)
        assert jl_path.exists(), f"{folder}: .jl file was not created"
        assert jl_path.suffix == ".jl"

    @pytest.mark.parametrize(
        "folder,mdl_path",
        _all_mdl_files(),
        ids=[f for f, _ in _all_mdl_files()],
    )
    @pytest.mark.filterwarnings("ignore::UserWarning")
    def test_jl_contains_required_sections(self, folder, mdl_path, tmp_path):
        """Generated .jl must contain the structural markers of a valid MTK model."""
        import shutil as _shutil
        dst = tmp_path / mdl_path.name
        _shutil.copy(mdl_path, dst)

        from pysd import translate_to_julia

        jl_path = translate_to_julia(dst)
        content = jl_path.read_text()

        assert "using ModelingToolkit" in content, f"{folder}: missing 'using ModelingToolkit'"
        assert "ODESystem" in content, f"{folder}: missing 'ODESystem'"
        assert "run_model" in content, f"{folder}: missing 'run_model'"
        assert "@variables t" in content, f"{folder}: missing '@variables t'"


class TestTranslationCleanModels:
    """Models in CLEAN_MODELS must translate with zero UserWarnings."""

    @pytest.mark.parametrize(
        "folder,mdl_path",
        [(f, p) for f, p in _all_mdl_files() if f in CLEAN_MODELS],
        ids=[f for f, _ in _all_mdl_files() if f in CLEAN_MODELS],
    )
    def test_no_warnings(self, folder, mdl_path, tmp_path):
        """Clean models must not emit any UserWarning during translation."""
        import shutil as _shutil
        dst = tmp_path / mdl_path.name
        _shutil.copy(mdl_path, dst)

        from pysd import translate_to_julia

        # With filterwarnings=error in pytest.ini, any UserWarning becomes an
        # error, so we just call translate_to_julia normally.
        jl_path = translate_to_julia(dst)
        assert jl_path.exists()

    @pytest.mark.parametrize(
        "folder,mdl_path",
        [(f, p) for f, p in _all_mdl_files() if f in CLEAN_MODELS],
        ids=[f for f, _ in _all_mdl_files() if f in CLEAN_MODELS],
    )
    def test_stocks_declared(self, folder, mdl_path, tmp_path):
        """Models with stocks must declare @variables ... (t) in the output."""
        import shutil as _shutil
        dst = tmp_path / mdl_path.name
        _shutil.copy(mdl_path, dst)

        from pysd import translate_to_julia

        jl_path = translate_to_julia(dst)
        content = jl_path.read_text()
        # Every model has at minimum the ODESystem boilerplate
        assert "ODESystem" in content

    @pytest.mark.parametrize(
        "folder,mdl_path",
        [(f, p) for f, p in _all_mdl_files() if f in CLEAN_MODELS],
        ids=[f for f, _ in _all_mdl_files() if f in CLEAN_MODELS],
    )
    def test_control_vars_emitted(self, folder, mdl_path, tmp_path):
        """Control variables (initial/final time, dt) must appear in output."""
        import shutil as _shutil
        dst = tmp_path / mdl_path.name
        _shutil.copy(mdl_path, dst)

        from pysd import translate_to_julia

        jl_path = translate_to_julia(dst)
        content = jl_path.read_text()
        assert "initial_time" in content
        assert "final_time" in content
        assert "time_step" in content


# ---------------------------------------------------------------------------
# Tier 1 — Feature-specific translation tests
# ---------------------------------------------------------------------------

class TestTranslationFeatures:
    """Spot-check that specific SD constructs produce the expected Julia output."""

    def _translate(self, folder: str, tmp_path: Path) -> str:
        import shutil as _shutil
        mdl = next((TEST_MODELS_DIR / folder).glob("*.mdl"))
        dst = tmp_path / mdl.name
        _shutil.copy(mdl, dst)
        from pysd import translate_to_julia
        return translate_to_julia(dst).read_text()

    def test_integ_emits_ode(self, tmp_path):
        content = self._translate("abs", tmp_path)
        assert "D(" in content, "INTEG must produce a D(x) ~ ... ODE equation"

    def test_lookup_emits_interpolation(self, tmp_path):
        content = self._translate("lookups_inline", tmp_path)
        assert "LinearInterpolation" in content
        assert "DataInterpolations" in content

    def test_smooth_emits_auxiliary_stocks(self, tmp_path):
        content = self._translate("smooth_and_stock", tmp_path)
        assert "_lv" in content, "SMOOTH must introduce auxiliary level stocks"

    def test_xidz_emits_helper(self, tmp_path):
        content = self._translate("xidz_zidz", tmp_path)
        assert "_xidz" in content or "_zidz" in content

    def test_input_functions_emit_helpers(self, tmp_path):
        content = self._translate("input_functions", tmp_path)
        assert "_pulse(" in content or "_ramp(" in content or "_step(" in content

    def test_if_then_else_maps_to_ifelse(self, tmp_path):
        content = self._translate("if_stmt", tmp_path)
        assert "ifelse(" in content

    def test_logicals_map_to_julia_operators(self, tmp_path):
        content = self._translate("logicals", tmp_path)
        # AND / OR should map to && / ||
        assert "&&" in content or "||" in content or "!" in content

    def test_lookup_with_expr_emits_interpolation(self, tmp_path):
        content = self._translate("lookups_with_expr", tmp_path)
        assert "LinearInterpolation" in content

    def test_game_passthrough(self, tmp_path):
        """GAME should not break translation."""
        content = self._translate("game", tmp_path)
        assert "ODESystem" in content

    @pytest.mark.filterwarnings("ignore::UserWarning")
    def test_delay_emits_pipeline_levels(self, tmp_path):
        """DELAY1 / DELAY3 expand into auxiliary _dl level stocks."""
        content = self._translate("delays", tmp_path)
        assert "_dl" in content, "DELAY must introduce pipeline level variables"
        assert "D(_dl" in content, "each DELAY level must have its own ODE"


# ---------------------------------------------------------------------------
# Tier 1 — Modular (split-views) translation
# ---------------------------------------------------------------------------

class TestModularTranslation:
    """split_views=True must create a main .jl file plus per-view module files."""

    def test_split_model_creates_modules_dir(self, tmp_path):
        import shutil as _shutil
        src = Path("tests/more-tests/split_model/test_split_model.mdl")
        if not src.exists():
            pytest.skip("split_model fixture not available")

        dst = tmp_path / src.name
        _shutil.copy(src, dst)

        from pysd import translate_to_julia

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            jl_path = translate_to_julia(dst, split_views=True)

        modules_dir = tmp_path / f"modules_{dst.stem}"
        assert jl_path.exists()
        assert modules_dir.exists(), "modules directory must be created for split models"

    def test_split_model_module_files_exist(self, tmp_path):
        import shutil as _shutil
        src = Path("tests/more-tests/split_model/test_split_model.mdl")
        if not src.exists():
            pytest.skip("split_model fixture not available")

        dst = tmp_path / src.name
        _shutil.copy(src, dst)

        from pysd import translate_to_julia

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            translate_to_julia(dst, split_views=True)

        modules_dir = tmp_path / f"modules_{dst.stem}"
        jl_files = list(modules_dir.rglob("*.jl"))
        assert len(jl_files) > 0, "at least one module .jl file must be created"

    def test_split_model_main_includes_modules(self, tmp_path):
        import shutil as _shutil
        src = Path("tests/more-tests/split_model/test_split_model.mdl")
        if not src.exists():
            pytest.skip("split_model fixture not available")

        dst = tmp_path / src.name
        _shutil.copy(src, dst)

        from pysd import translate_to_julia

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            jl_path = translate_to_julia(dst, split_views=True)

        content = jl_path.read_text()
        assert "include(" in content

    def test_split_model_all_declarations_in_main(self, tmp_path):
        """Variable declarations must be in the main file so all modules can reference them."""
        import shutil as _shutil
        src = Path("tests/more-tests/split_model/test_split_model.mdl")
        if not src.exists():
            pytest.skip("split_model fixture not available")

        dst = tmp_path / src.name
        _shutil.copy(src, dst)

        from pysd import translate_to_julia

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            jl_path = translate_to_julia(dst, split_views=True)

        content = jl_path.read_text()
        assert "@variables" in content
        assert "ODESystem" in content


# ---------------------------------------------------------------------------
# Tier 2 — Numerical validation (requires Julia)
# ---------------------------------------------------------------------------

def _julia_runner_script(model_jl: Path, col_names: List[str],
                         julia_ids: List[str], t_ref: List[float]) -> str:
    """
    Generate a self-contained Julia script that:
      1. includes the generated model file
      2. runs the model with the Euler solver
      3. prints a CSV with Time + one column per variable
         (using MTK symbolic indexing — works for both stocks and observed vars)
    """
    t_array = "[" + ", ".join(str(t) for t in t_ref) + "]"

    col_header = ", ".join(f'"{c}"' for c in col_names)
    sym_exprs = ", ".join(f"sys.{j}" for j in julia_ids)

    return f"""\
include("{model_jl.as_posix()}")

using Printf

sol = run_model(; solver=Euler())

col_names = [{col_header}]
col_syms  = [{sym_exprs}]
t_ref     = {t_array}

# header
print("Time")
for n in col_names
    print(",", n)
end
println()

# rows
for t in t_ref
    @printf("%g", t)
    for sym in col_syms
        try
            val = sol[sym, :][argmin(abs.(sol.t .- t))]
            @printf(",%g", val)
        catch
            @printf(",NaN")
        end
    end
    println()
end
"""


def _run_julia(script_path: Path, timeout: int = 120) -> str:
    """Run a Julia script and return its stdout, raising on non-zero exit."""
    result = subprocess.run(
        ["julia", "--startup-file=no", str(script_path)],
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Julia script failed (exit {result.returncode}):\n"
            f"STDOUT: {result.stdout[:500]}\n"
            f"STDERR: {result.stderr[:500]}"
        )
    return result.stdout


def _parse_csv_from_string(text: str) -> Dict[str, List[float]]:
    result: Dict[str, List[float]] = {}
    reader = csv.DictReader(io.StringIO(text.strip()))
    for row in reader:
        for k, v in row.items():
            try:
                result.setdefault(k, []).append(float(v))
            except ValueError:
                result.setdefault(k, []).append(float("nan"))
    return result


@pytest.mark.julia
@pytest.mark.skipif(
    not _julia_mtk_available(),
    reason="julia binary not found or ModelingToolkit.jl / OrdinaryDiffEq.jl not installed",
)
class TestNumericalValidation:
    """
    Numerical validation against output.csv reference values.

    Each test translates a .mdl, runs it in Julia (Euler solver), and
    checks every variable column against the reference with rel_tol=1e-3.

    The time column in output.csv determines the comparison time points;
    if SAVEPER > TIME STEP the solution is sampled at the saved instants.
    """

    def _get_julia_ids(self, folder: str, ref_cols: List[str]) -> Dict[str, str]:
        """
        Map output.csv column names → Julia identifiers via JuliaNamespaceManager.
        Build the namespace by running the parser on the model (without writing
        the .jl file) so we get the exact same namespace the builder uses.
        """
        from pysd.builders.julia.namespace import JuliaNamespaceManager
        from pysd.translators.vensim.vensim_file import VensimFile

        mdl = next((TEST_MODELS_DIR / folder).glob("*.mdl"))
        vf = VensimFile(mdl)
        vf.parse()
        am = vf.get_abstract_model()

        ns = JuliaNamespaceManager()
        for section in am.sections:
            for elem in section.elements:
                ns.add_to_namespace(elem.name)

        mapping = {}
        for col in ref_cols:
            if col.lower() == "time":
                continue
            julia_id = ns.get(col)
            if julia_id:
                mapping[col] = julia_id
        return mapping

    def _run_model(self, folder: str, tmp_path: Path) -> Tuple[Dict, Dict]:
        """
        Returns (reference, simulated) dicts: {col_name: [float, ...]}
        """
        import shutil as _shutil
        from pysd import translate_to_julia

        mdl = next((TEST_MODELS_DIR / folder).glob("*.mdl"))
        dst = tmp_path / mdl.name
        _shutil.copy(mdl, dst)

        jl_path = translate_to_julia(dst)

        ref = _read_csv(TEST_MODELS_DIR / folder / "output.csv")
        t_ref = ref["Time"]

        id_map = self._get_julia_ids(folder, list(ref.keys()))
        if not id_map:
            pytest.skip(f"{folder}: no variables could be mapped to Julia identifiers")

        col_names = list(id_map.keys())
        julia_ids = [id_map[c] for c in col_names]

        runner = _julia_runner_script(jl_path, col_names, julia_ids, t_ref)
        runner_path = tmp_path / "_runner.jl"
        runner_path.write_text(runner)

        stdout = _run_julia(runner_path)
        simulated = _parse_csv_from_string(stdout)
        return ref, simulated

    def _compare(self, folder: str, ref: Dict, sim: Dict,
                 rtol: float = 1e-3, atol: float = 1e-4) -> None:
        """Assert all shared columns match within tolerance."""
        IGNORABLE = {"saveper", "initial_time", "final_time", "time_step", "time"}
        failures = []

        for col, ref_vals in ref.items():
            if col.lower() in IGNORABLE:
                continue
            if col not in sim:
                continue  # variable not accessible — skip rather than fail

            sim_vals = sim[col]
            if len(ref_vals) != len(sim_vals):
                failures.append(
                    f"{col}: length mismatch ({len(ref_vals)} vs {len(sim_vals)})"
                )
                continue

            for i, (r, s) in enumerate(zip(ref_vals, sim_vals)):
                if not _isclose(r, s, rtol=rtol, atol=atol):
                    failures.append(
                        f"{col}[{i}]: expected {r}, got {s} (t={ref['Time'][i]})"
                    )

        assert not failures, (
            f"{folder}: {len(failures)} comparison failure(s):\n"
            + "\n".join(failures[:10])
            + ("\n..." if len(failures) > 10 else "")
        )

    # --- one test method per numerical model ---

    def test_abs(self, tmp_path):
        ref, sim = self._run_model("abs", tmp_path)
        self._compare("abs", ref, sim)

    def test_builtin_max(self, tmp_path):
        ref, sim = self._run_model("builtin_max", tmp_path)
        self._compare("builtin_max", ref, sim)

    def test_builtin_min(self, tmp_path):
        ref, sim = self._run_model("builtin_min", tmp_path)
        self._compare("builtin_min", ref, sim)

    def test_exp(self, tmp_path):
        ref, sim = self._run_model("exp", tmp_path)
        self._compare("exp", ref, sim)

    def test_if_stmt(self, tmp_path):
        ref, sim = self._run_model("if_stmt", tmp_path)
        self._compare("if_stmt", ref, sim)

    def test_initial_function(self, tmp_path):
        ref, sim = self._run_model("initial_function", tmp_path)
        self._compare("initial_function", ref, sim)

    def test_input_functions(self, tmp_path):
        """PULSE, RAMP, STEP helpers produce correct time series."""
        ref, sim = self._run_model("input_functions", tmp_path)
        self._compare("input_functions", ref, sim)

    def test_logicals(self, tmp_path):
        ref, sim = self._run_model("logicals", tmp_path)
        self._compare("logicals", ref, sim)

    def test_lookups_with_expr(self, tmp_path):
        ref, sim = self._run_model("lookups_with_expr", tmp_path)
        self._compare("lookups_with_expr", ref, sim)

    def test_number_handling(self, tmp_path):
        """XIDZ / ZIDZ and numeric edge cases produce correct values."""
        ref, sim = self._run_model("number_handling", tmp_path)
        self._compare("number_handling", ref, sim)

    def test_sqrt(self, tmp_path):
        ref, sim = self._run_model("sqrt", tmp_path)
        self._compare("sqrt", ref, sim)

    def test_trig(self, tmp_path):
        ref, sim = self._run_model("trig", tmp_path)
        self._compare("trig", ref, sim)
